CITY_TO_IATA = {
    "amsterdam": "AMS",
    "lisbon": "LIS",
    "barcelona": "BCN",
    "paris": "PAR",
    "rome": "ROM",
    "berlin": "BER",
    "london": "LON",
    "vienna": "VIE",
    "madrid": "MAD",
    "copenhagen": "CPH",
    "stockholm": "STO",
    "prague": "PRG",
    "budapest": "BUD",
    "munich": "MUC",
    "brussels": "BRU",
    "new york": "NYC",
    "tokyo": "TYO",
    "dubai": "DXB",
    "edinburgh": "EDI",
    "dublin": "DUB",
    "warsaw": "WAW",
}

IATA_TO_CITY = {
    code: city.title()
    for city, code in CITY_TO_IATA.items()
}
IATA_TO_CITY.update({"PAR": "Paris", "ROM": "Rome", "NYC": "New York", "TYO": "Tokyo"})

CITY_COUNTRY = {
    "amsterdam": "Netherlands",
    "lisbon": "Portugal",
    "barcelona": "Spain",
    "paris": "France",
    "rome": "Italy",
    "berlin": "Germany",
    "london": "United Kingdom",
    "vienna": "Austria",
    "madrid": "Spain",
    "copenhagen": "Denmark",
    "stockholm": "Sweden",
    "prague": "Czech Republic",
    "budapest": "Hungary",
    "munich": "Germany",
    "brussels": "Belgium",
    "new york": "United States",
    "tokyo": "Japan",
    "dubai": "United Arab Emirates",
    "edinburgh": "United Kingdom",
    "dublin": "Ireland",
    "warsaw": "Poland",
}

CITY_COORDS = {
    "berlin": (52.5200, 13.4050),
    "amsterdam": (52.3676, 4.9041),
    "paris": (48.8566, 2.3522),
    "london": (51.5072, -0.1276),
    "barcelona": (41.3874, 2.1686),
    "lisbon": (38.7223, -9.1393),
    "rome": (41.9028, 12.4964),
    "madrid": (40.4168, -3.7038),
    "vienna": (48.2082, 16.3738),
    "prague": (50.0755, 14.4378),
    "zurich": (47.3769, 8.5417),
    "munich": (48.1351, 11.5820),
    "frankfurt": (50.1109, 8.6821),
    "hamburg": (53.5511, 9.9937),
}

ECO_KEYWORDS = {
    "green key",
    "earthcheck",
    "leed",
    "iso 14001",
    "biosphere",
    "travelife",
    "rainforest alliance",
    "eco",
    "sustainable",
    "green",
    "organic",
    "boutique",
}

ZERO_CARBON_MODES = {"walk", "walking", "bike", "bicycle", "cycling"}

FALLBACK_FACTORS_KG_PER_KM = {
    "flight": 0.25,
    "train": 0.04,
    "bus": 0.08,
    "car": 0.18,
    "taxi": 0.20,
    "ferry": 0.19,
}

TRANSPORT_MODE_ALIASES = {
    "plane": "flight",
    "airplane": "flight",
    "air": "flight",
    "flight": "flight",
    "train": "train",
    "rail": "train",
    "bus": "bus",
    "coach": "bus",
    "car": "car",
    "drive": "car",
    "driving": "car",
    "taxi": "taxi",
    "cab": "taxi",
    "ferry": "ferry",
    "boat": "ferry",
    "walk": "walk",
    "walking": "walk",
    "bike": "bike",
    "bicycle": "bike",
    "cycling": "bike",
}

MODE_TEMPLATES = [
    ("train", "Regional / intercity rail", 0.95),
    ("bus", "Coach / intercity bus", 0.78),
    ("flight", "Short-haul flight", 0.22),
    ("car", "Private car (avg. occupancy)", 0.45),
    ("electric_car", "Electric car", 0.70),
    ("ferry", "Ferry (if coastal)", 0.50),
    ("walking", "Walking / on foot", 1.0),
]

KNOWN_CITIES = [
    "amsterdam",
    "lisbon",
    "barcelona",
    "paris",
    "rome",
    "berlin",
    "london",
    "vienna",
    "madrid",
    "copenhagen",
    "stockholm",
    "prague",
    "budapest",
    "munich",
    "brussels",
    "new york",
    "tokyo",
    "dubai",
    "edinburgh",
    "dublin",
    "warsaw",
    "zurich",
    "reykjavik",
    "tallinn",
    "florence",
    "potsdam",
    "hamburg",
    "frankfurt",
    "cologne",
    "dusseldorf",
    "stuttgart",
    "japan",
    "portugal",
    "spain",
    "france",
    "italy",
    "germany",
    "netherlands",
    "united kingdom",
    "uk",
    "austria",
    "denmark",
    "sweden",
    "czech republic",
    "hungary",
    "united states",
    "usa",
    "ireland",
    "poland",
    "switzerland",
]

PARSER_TRANSPORT_ALIASES = {
    "flight": ("flight", "fly", "flying", "plane", "airplane"),
    "train": ("train", "rail"),
    "bus": ("bus", "coach"),
    "car": ("car", "driving", "drive"),
    "electric_car": ("electric car", "ev"),
    "ferry": ("ferry", "boat"),
    "walking": ("walking", "walk", "on foot", "by foot", "travel via foot"),
    "cycling": ("cycling", "cycle", "bike", "bicycle", "by bike"),
}

MONTHS = {
    "jan": 1,
    "january": 1,
    "feb": 2,
    "february": 2,
    "mar": 3,
    "march": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "sep": 9,
    "september": 9,
    "oct": 10,
    "october": 10,
    "nov": 11,
    "november": 11,
    "dec": 12,
    "december": 12,
}
