version: "3.1"

assistant_id: nova-plan-assistant

recipe: default.v1

language: en

pipeline:
  - name: CompactLLMCommandGenerator
    llm:
      model_group: llm_models_grp
    flow_retrieval:
      active: false

policies:
  - name: FlowPolicy